export const feelingTips = [
  { type: 'sad', text: 'sad1' },
  { type: 'sad', text: 'sad2' },
  { type: 'sad', text: 'sad3' },
  { type: 'sad', text: 'sad4' },
  { type: 'sad', text: 'sad5' },
  { type: 'sad', text: 'sad6' },
  { type: 'sad', text: 'sad7' },
  { type: 'normal', text: 'normal1' },
  { type: 'normal', text: 'normal2' },
  { type: 'normal', text: 'normal3' },
  { type: 'normal', text: 'normal4' },
  { type: 'normal', text: 'normal5' },
  { type: 'normal', text: 'normal6' },
  { type: 'normal', text: 'normal7' },
  { type: 'happy', text: 'happy1' },
  { type: 'happy', text: 'happy2' },
  { type: 'happy', text: 'happy3' },
  { type: 'happy', text: 'happy4' },
  { type: 'happy', text: 'happy5' },
  { type: 'happy', text: 'happy6' },
  { type: 'happy', text: 'happy7' },
]
